pub mod activity_logs;
pub mod answer_key_acceptable_answers;
pub mod answer_keys;
pub mod assessment_questions;
pub mod assessment_submissions;
pub mod assessments;
pub mod assignment_submissions;
pub mod assignments_hw;
pub mod class_participants;
pub mod classes;
pub mod grade_components_config;
pub mod grade_items;
pub mod grade_scores;
pub mod learning_materials;
pub mod login_attempts;
pub mod material_files;
pub mod quarterly_grades;
pub mod question_choices;
pub mod refresh_tokens;
pub mod school_settings;
pub mod submission_answer_items;
pub mod submission_answers;
pub mod submission_files;
pub mod table_of_specifications;
pub mod tos_competencies;
pub mod users;

pub use activity_logs::Entity as ActivityLogs;
pub use answer_key_acceptable_answers::Entity as AnswerKeyAcceptableAnswers;
pub use answer_keys::Entity as AnswerKeys;
pub use assessment_questions::Entity as AssessmentQuestions;
pub use assessment_submissions::Entity as AssessmentSubmissions;
pub use assessments::Entity as Assessments;
pub use assignment_submissions::Entity as AssignmentSubmissions;
pub use assignments_hw::Entity as AssignmentsHw;
pub use class_participants::Entity as ClassParticipants;
pub use classes::Entity as Classes;
pub use grade_components_config::Entity as GradeComponentsConfig;
pub use grade_items::Entity as GradeItems;
pub use grade_scores::Entity as GradeScores;
pub use learning_materials::Entity as LearningMaterials;
pub use login_attempts::Entity as LoginAttempts;
pub use material_files::Entity as MaterialFiles;
pub use quarterly_grades::Entity as QuarterlyGrades;
pub use question_choices::Entity as QuestionChoices;
pub use refresh_tokens::Entity as RefreshTokens;
pub use school_settings::Entity as SchoolSettings;
pub use submission_answer_items::Entity as SubmissionAnswerItems;
pub use submission_answers::Entity as SubmissionAnswers;
pub use submission_files::Entity as SubmissionFiles;
pub use table_of_specifications::Entity as TableOfSpecifications;
pub use tos_competencies::Entity as TosCompetencies;
pub use users::Entity as Users;

pub mod prelude {
    pub use super::activity_logs::{self, Entity as ActivityLogs};
    pub use super::answer_key_acceptable_answers::{self, Entity as AnswerKeyAcceptableAnswers};
    pub use super::answer_keys::{self, Entity as AnswerKeys};
    pub use super::assessment_questions::{self, Entity as AssessmentQuestions};
    pub use super::assessment_submissions::{self, Entity as AssessmentSubmissions};
    pub use super::assessments::{self, Entity as Assessments};
    pub use super::assignment_submissions::{self, Entity as AssignmentSubmissions};
    pub use super::assignments_hw::{self, Entity as AssignmentsHw};
    pub use super::class_participants::{self, Entity as ClassParticipants};
    pub use super::classes::{self, Entity as Classes};
    pub use super::grade_components_config::{self, Entity as GradeComponentsConfig};
    pub use super::grade_items::{self, Entity as GradeItems};
    pub use super::grade_scores::{self, Entity as GradeScores};
    pub use super::learning_materials::{self, Entity as LearningMaterials};
    pub use super::login_attempts::{self, Entity as LoginAttempts};
    pub use super::material_files::{self, Entity as MaterialFiles};
    pub use super::quarterly_grades::{self, Entity as QuarterlyGrades};
    pub use super::question_choices::{self, Entity as QuestionChoices};
    pub use super::refresh_tokens::{self, Entity as RefreshTokens};
    pub use super::school_settings::{self, Entity as SchoolSettings};
    pub use super::submission_answer_items::{self, Entity as SubmissionAnswerItems};
    pub use super::submission_answers::{self, Entity as SubmissionAnswers};
    pub use super::submission_files::{self, Entity as SubmissionFiles};
    pub use super::table_of_specifications::{self, Entity as TableOfSpecifications};
    pub use super::tos_competencies::{self, Entity as TosCompetencies};
    pub use super::users::{self, Entity as Users};
}
